language: go

go:
    - 1.5.1
    - 1.6.3
    - tip

os:
    - linux
    - osx

go_import_path: github.com/elemc/gotelegrambot

install:
    - go get github.com/couchbase/gocb
    - go get gopkg.in/telegram-bot-api.v4
    - go get github.com/gin-gonic/gin

script: go build
