language: go

go:
    - 1.5.1
    - release
    - tip

go_import_path: github.com/elemc/gotelegrambot

install:
    - go get github.com/couchbase/gocb
    - go get gopkg.in/telegram-bot-api.v4
    - go get github.com/gin-gonic/gin
